CREATE TABLE TAB_FATURAMENTO
(DATA_VENDA DATE NULL, TOTAL_VENDA FLOAT);

SELECT * FROM NOTAS;
SELECT * FROM ITENS_NOTAS;

DELETE * FROM NOTAS;
DELETE * FROM ITENS_NOTAS;

INSERT INTO NOTAS (NUMERO, DATA_VENDA, CPF, MATRICULA, IMPOSTO)
VALUES ('0103', '2019-05-08', '1471156710', '235', 0.10);
INSERT INTO ITENS_NOTAS (NUMERO, CODIGO, QUANTIDADE, PRECO)
VALUES ('0103', '1000889', 100, 10);
INSERT INTO ITENS_NOTAS (NUMERO, CODIGO, QUANTIDADE, PRECO)
VALUES ('0103', '10002334', 100, 10);
INSERT INTO ITENS_NOTAS (NUMERO, CODIGO, QUANTIDADE, PRECO)
VALUES ('0103', '10002334', 100, 10);

INSERT INTO TAB_FATURAMENTO
SELECT A.DATA_VENDA, SUM(QUANTIDADE * B.PRECO) AS TOTAL_VENDA FROM 
NOTAS A INNER JOIN ITENS_NOTAS B
ON A.NUMERO = B.NUMERO
GROUP BY A.DATA_VENDA;



SELECT * FROM TAB_FATURAMENTO;

DELIMITER // 
CREATE TRIGGER TG_CALCULA_FATURAMENTO_INSERT AFTER INSERT ON itens_notas
FOR EACH ROW BEGIN
DELETE FROM TAB_FATURAMENTO;
SELECT A.DATA_VENDA, SUM(B.QUANTIDADE * B.PRECO) AS TOTAL_VENDA FROM
NOTAS A INNER JOIN NOTAS B
ON A.NUMERO = B.NUMERO
GROUP BY A.DATA_VENDA;
END//